# Generated by Django 3.2.24 on 2024-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='max_uses',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='visitor',
            name='uses_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
